// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: db.proto

package server

import (
	"context"

	"skeyevss/core/app/sev/db/db"
	"skeyevss/core/app/sev/db/internal/logic/configservice"
	"skeyevss/core/app/sev/db/internal/svc"
)

type ConfigServiceServer struct {
	svcCtx *svc.ServiceContext
	db.UnimplementedConfigServiceServer
}

func NewConfigServiceServer(svcCtx *svc.ServiceContext) *ConfigServiceServer {
	return &ConfigServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取uniqueId
func (s *ConfigServiceServer) MaxId(ctx context.Context, in *db.TypeReq) (*db.Response, error) {
	l := configservicelogic.NewMaxIdLogic(ctx, s.svcCtx)
	return l.MaxId(in)
}

// 字典创建
func (s *ConfigServiceServer) DictionaryCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := configservicelogic.NewDictionaryCreateLogic(ctx, s.svcCtx)
	return l.DictionaryCreate(in)
}

// 字典删除
func (s *ConfigServiceServer) DictionaryDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewDictionaryDeleteLogic(ctx, s.svcCtx)
	return l.DictionaryDelete(in)
}

// 字典更新
func (s *ConfigServiceServer) DictionaryUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewDictionaryUpdateLogic(ctx, s.svcCtx)
	return l.DictionaryUpdate(in)
}

// 管理员详情
func (s *ConfigServiceServer) DictionaryRow(ctx context.Context, in *db.IDReq) (*db.Response, error) {
	l := configservicelogic.NewDictionaryRowLogic(ctx, s.svcCtx)
	return l.DictionaryRow(in)
}

// 字典列表
func (s *ConfigServiceServer) Dictionaries(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewDictionariesLogic(ctx, s.svcCtx)
	return l.Dictionaries(in)
}

// 字典结构树
func (s *ConfigServiceServer) DictionaryTrees(ctx context.Context, in *db.EmptyRequest) (*db.Response, error) {
	l := configservicelogic.NewDictionaryTreesLogic(ctx, s.svcCtx)
	return l.DictionaryTrees(in)
}

// 字典检查uniqueId是否存在
func (s *ConfigServiceServer) DictionaryCheckUniqueId(ctx context.Context, in *db.UniqueIdReq) (*db.Response, error) {
	l := configservicelogic.NewDictionaryCheckUniqueIdLogic(ctx, s.svcCtx)
	return l.DictionaryCheckUniqueId(in)
}

// 设置更新
func (s *ConfigServiceServer) SettingUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewSettingUpdateLogic(ctx, s.svcCtx)
	return l.SettingUpdate(in)
}

// 设置获取
func (s *ConfigServiceServer) SettingRow(ctx context.Context, in *db.EmptyRequest) (*db.Response, error) {
	l := configservicelogic.NewSettingRowLogic(ctx, s.svcCtx)
	return l.SettingRow(in)
}

// 任务创建
func (s *ConfigServiceServer) CrontabCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := configservicelogic.NewCrontabCreateLogic(ctx, s.svcCtx)
	return l.CrontabCreate(in)
}

// 任务删除
func (s *ConfigServiceServer) CrontabDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewCrontabDeleteLogic(ctx, s.svcCtx)
	return l.CrontabDelete(in)
}

// 任务更新
func (s *ConfigServiceServer) CrontabUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewCrontabUpdateLogic(ctx, s.svcCtx)
	return l.CrontabUpdate(in)
}

// 任务批量更新
func (s *ConfigServiceServer) CrontabBulkUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewCrontabBulkUpdateLogic(ctx, s.svcCtx)
	return l.CrontabBulkUpdate(in)
}

// 任务详情
func (s *ConfigServiceServer) CrontabRow(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewCrontabRowLogic(ctx, s.svcCtx)
	return l.CrontabRow(in)
}

// 任务列表
func (s *ConfigServiceServer) CrontabList(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewCrontabListLogic(ctx, s.svcCtx)
	return l.CrontabList(in)
}

// 所有数据
func (s *ConfigServiceServer) Crontab(ctx context.Context, in *db.EmptyRequest) (*db.Response, error) {
	l := configservicelogic.NewCrontabLogic(ctx, s.svcCtx)
	return l.Crontab(in)
}

// media server创建
func (s *ConfigServiceServer) MsCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := configservicelogic.NewMsCreateLogic(ctx, s.svcCtx)
	return l.MsCreate(in)
}

// media server删除
func (s *ConfigServiceServer) MsDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewMsDeleteLogic(ctx, s.svcCtx)
	return l.MsDelete(in)
}

// media server更新
func (s *ConfigServiceServer) MsUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewMsUpdateLogic(ctx, s.svcCtx)
	return l.MsUpdate(in)
}

// media server详情
func (s *ConfigServiceServer) MsRow(ctx context.Context, in *db.IDReq) (*db.Response, error) {
	l := configservicelogic.NewMsRowLogic(ctx, s.svcCtx)
	return l.MsRow(in)
}

// media server列表
func (s *ConfigServiceServer) MsList(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewMsListLogic(ctx, s.svcCtx)
	return l.MsList(in)
}

// media server option 列表
func (s *ConfigServiceServer) MsOptions(ctx context.Context, in *db.EmptyRequest) (*db.Response, error) {
	l := configservicelogic.NewMsOptionsLogic(ctx, s.svcCtx)
	return l.MsOptions(in)
}

// 录像计划创建
func (s *ConfigServiceServer) VideoProjectCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := configservicelogic.NewVideoProjectCreateLogic(ctx, s.svcCtx)
	return l.VideoProjectCreate(in)
}

// 录像计划删除
func (s *ConfigServiceServer) VideoProjectDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewVideoProjectDeleteLogic(ctx, s.svcCtx)
	return l.VideoProjectDelete(in)
}

// 录像计划更新
func (s *ConfigServiceServer) VideoProjectUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewVideoProjectUpdateLogic(ctx, s.svcCtx)
	return l.VideoProjectUpdate(in)
}

// 录像计划详情
func (s *ConfigServiceServer) VideoProjectRow(ctx context.Context, in *db.IDReq) (*db.Response, error) {
	l := configservicelogic.NewVideoProjectRowLogic(ctx, s.svcCtx)
	return l.VideoProjectRow(in)
}

// 录像计划列表
func (s *ConfigServiceServer) VideoProjectList(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := configservicelogic.NewVideoProjectListLogic(ctx, s.svcCtx)
	return l.VideoProjectList(in)
}
