// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: db.proto

package backendservice

import (
	"context"

	"skeyevss/core/app/sev/db/db"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminPasswordReq          = db.AdminPasswordReq
	DeviceChannelReq          = db.DeviceChannelReq
	EmptyRequest              = db.EmptyRequest
	IDReq                     = db.IDReq
	IdsReq                    = db.IdsReq
	LoginReq                  = db.LoginReq
	MapReq                    = db.MapReq
	PermissionItem            = db.PermissionItem
	PermissionResourceInitReq = db.PermissionResourceInitReq
	Response                  = db.Response
	SliceMapReq               = db.SliceMapReq
	TypeReq                   = db.TypeReq
	UniqueIdReq               = db.UniqueIdReq
	UniqueIdsReq              = db.UniqueIdsReq
	XConditionItem            = db.XConditionItem
	XConditionOriginalItem    = db.XConditionOriginalItem
	XOrderItem                = db.XOrderItem
	XRequestParams            = db.XRequestParams
	XResponse                 = db.XResponse
	XUpdateItem               = db.XUpdateItem

	BackendService interface {
		// 后台登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*Response, error)
		// 获取所有权限相关
		AuthRes(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error)
		// 组织部门创建
		DepartmentCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 组织部门删除
		DepartmentDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 组织部门修改
		DepartmentUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 组织部门详情
		DepartmentRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error)
		// 组织部门列表
		Departments(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 组织部门结构树
		DepartmentTrees(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*Response, error)
		// 角色创建
		RoleCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 角色删除
		RoleDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 角色修改
		RoleUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 角色详情
		RoleRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error)
		// 角色列表
		Roles(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 管理员创建
		AdminCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 管理员删除
		AdminDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 管理员修改
		AdminUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 管理员详情
		AdminRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error)
		// 管理员列表
		Admins(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 更新密码
		AdminPassword(ctx context.Context, in *AdminPasswordReq, opts ...grpc.CallOption) (*Response, error)
		// 检查用户是否存在
		AdminCheckExists(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 初始化密码
		InitializeSetPassword(ctx context.Context, in *AdminPasswordReq, opts ...grpc.CallOption) (*Response, error)
		// 操作日志创建
		SystemOperationLogCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 操作日志列表
		SystemOperationLogs(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
	}

	defaultBackendService struct {
		cli zrpc.Client
	}
)

func NewBackendService(cli zrpc.Client) BackendService {
	return &defaultBackendService{
		cli: cli,
	}
}

// 后台登录
func (m *defaultBackendService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取所有权限相关
func (m *defaultBackendService) AuthRes(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.AuthRes(ctx, in, opts...)
}

// 组织部门创建
func (m *defaultBackendService) DepartmentCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.DepartmentCreate(ctx, in, opts...)
}

// 组织部门删除
func (m *defaultBackendService) DepartmentDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.DepartmentDelete(ctx, in, opts...)
}

// 组织部门修改
func (m *defaultBackendService) DepartmentUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.DepartmentUpdate(ctx, in, opts...)
}

// 组织部门详情
func (m *defaultBackendService) DepartmentRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.DepartmentRow(ctx, in, opts...)
}

// 组织部门列表
func (m *defaultBackendService) Departments(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.Departments(ctx, in, opts...)
}

// 组织部门结构树
func (m *defaultBackendService) DepartmentTrees(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.DepartmentTrees(ctx, in, opts...)
}

// 角色创建
func (m *defaultBackendService) RoleCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.RoleCreate(ctx, in, opts...)
}

// 角色删除
func (m *defaultBackendService) RoleDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.RoleDelete(ctx, in, opts...)
}

// 角色修改
func (m *defaultBackendService) RoleUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.RoleUpdate(ctx, in, opts...)
}

// 角色详情
func (m *defaultBackendService) RoleRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.RoleRow(ctx, in, opts...)
}

// 角色列表
func (m *defaultBackendService) Roles(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.Roles(ctx, in, opts...)
}

// 管理员创建
func (m *defaultBackendService) AdminCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.AdminCreate(ctx, in, opts...)
}

// 管理员删除
func (m *defaultBackendService) AdminDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.AdminDelete(ctx, in, opts...)
}

// 管理员修改
func (m *defaultBackendService) AdminUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.AdminUpdate(ctx, in, opts...)
}

// 管理员详情
func (m *defaultBackendService) AdminRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.AdminRow(ctx, in, opts...)
}

// 管理员列表
func (m *defaultBackendService) Admins(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.Admins(ctx, in, opts...)
}

// 更新密码
func (m *defaultBackendService) AdminPassword(ctx context.Context, in *AdminPasswordReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.AdminPassword(ctx, in, opts...)
}

// 检查用户是否存在
func (m *defaultBackendService) AdminCheckExists(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.AdminCheckExists(ctx, in, opts...)
}

// 初始化密码
func (m *defaultBackendService) InitializeSetPassword(ctx context.Context, in *AdminPasswordReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.InitializeSetPassword(ctx, in, opts...)
}

// 操作日志创建
func (m *defaultBackendService) SystemOperationLogCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.SystemOperationLogCreate(ctx, in, opts...)
}

// 操作日志列表
func (m *defaultBackendService) SystemOperationLogs(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewBackendServiceClient(m.cli.Conn())
	return client.SystemOperationLogs(ctx, in, opts...)
}
