Mode: "${SKEYEVSS_SERVER_ENV_MODE}"
ContainerizedState: ${SKEYEVSS_CONTAINERIZED_STATE}
Name: "${SKEYEVSS_GUARD_NAME}"
ProductName: "${SKEYEVSS_PRODUCT_NAME}"
InternalIP: "${SKEYEVSS_INTERNAL_IP}"
ExternalIP: "${SKEYEVSS_EXTERNAL_IP}"
Version: "${SKEYEVSS_VERSION}"
MinioApiTarget: "${SKEYEVSS_MINIO_API_TARGET}"

Log:
    KeepDays: 30
    Compress: true
    ServiceName: "${SKEYEVSS_GUARD_NAME}"
    Path: "${SKEYEVSS_SERVER_LOG_PATH}/${SKEYEVSS_GUARD_NAME}"
    Mode: "${SKEYEVSS_LOG_MODE}"
    Encoding: "${SKEYEVSS_LOG_ENCODING}"
    Level: "${SKEYEVSS_LOG_LEVEL}"

# service base config
SevBase:
    UseMysql: ${SKEYEVSS_ENABLED_MYSQL}
    UseRedis: ${SKEYEVSS_ENABLED_REDIS}
    UseFfmpeg: ${SKEYEVSS_ENABLED_FFMPEG}
    UseEtcd: ${SKEYEVSS_ENABLED_ETCD}
    # mysql sqlite
    DatabaseType: "${SKEYEVSS_DATABASE_TYPE}"

    Root: "${SKEYEVSS_ROOT}"
    MysqlUsername: "${SKEYEVSS_MYSQL_USERNAME}"
    MysqlPassword: "${SKEYEVSS_MYSQL_PASSWORD}"
    RedisPassword: "${SKEYEVSS_REDIS_PASSWORD}"

    SevNameMysql: "${SKEYEVSS_MYSQL_NAME}"
    SevNameRedis: "${SKEYEVSS_REDIS_NAME}"
    SevNameEtcd: "${SKEYEVSS_ETCD_NAME}"
    SevNameMediaServer: "${SKEYEVSS_MEDIA_SERVER_NAME}"
    SevNameGuard: "${SKEYEVSS_GUARD_NAME}"
    SevNameVss: "${SKEYEVSS_VSS_NAME}"
    SevNameCron: "${SKEYEVSS_CRON_NAME}"
    SevNameDB: "${SKEYEVSS_DB_GRPC_NAME}"
    SevNameBackendApi: "${SKEYEVSS_BACKEND_API_NAME}"
    SevNameWebSev: "${SKEYEVSS_WEB_SEV_NAME}"

    MysqlPort: ${SKEYEVSS_MYSQL_PORT}
    MysqlHost: ${SKEYEVSS_MYSQL_HOST}
    RedisPort: ${SKEYEVSS_REDIS_PORT}
    RedisHost: ${SKEYEVSS_REDIS_HOST}
    EtcdPort: ${SKEYEVSS_ETCD_CLIENT_PORT}
    WebSevPort: ${SKEYEVSS_WEB_SEV_PORT}
    MediaServerPort: ${SKEYEVSS_MEDIA_SERVER_PORT}
    VssPort: ${SKEYEVSS_VSS_PORT}
    CronPort: ${SKEYEVSS_CRON_PORT}
    GuardPort: ${SKEYEVSS_GUARD_PORT}
    DBPort: ${SKEYEVSS_DB_GRPC_PORT}
    BackendApiPort: ${SKEYEVSS_BACKEND_API_PORT}
    MediaServerHttpsPort: ${SKEYEVSS_MEDIA_SERVER_HTTPS_PORT}
    MediaServerRtspPort: ${SKEYEVSS_MEDIA_SERVER_RTSP_PORT}
    MediaServerRtmpPort: ${SKEYEVSS_MEDIA_SERVER_RTMP_PORT}
    MediaRtcIceHostNatToIps: "${SKEYEVSS_MEDIA_RTC_ICE_HOST_NAT_TO_IPS}"

    EtcdHost: "${SKEYEVSS_ETCD_HOST}"

    ProxyApiBase: "${SKEYEVSS_WEB_SEV_PROXY_API_BACKEND}"
    ProxyApiExternal: "${SKEYEVSS_WEB_SEV_PROXY_API_EXTERNAL}"
    ProxyFile: "${SKEYEVSS_WEB_SEV_PROXY_FILE}"
    ProxyFileUrl: "${SKEYEVSS_WEB_SEV_PROXY_FILE_URL}"
    ProxyApiExternalTarget: "${SKEYEVSS_WEB_SEV_PROXY_API_EXTERNAL_TARGET}"

    MSNotifyOnPubStart: "${SKEYEVSS_MEDIA_SERVER_NOTIFY_ON_PUB_START}"
    MSNotifyOnPubStop: "${SKEYEVSS_MEDIA_SERVER_NOTIFY_ON_PUB_STOP}"
    MSNotifyOnPushStart: "${SKEYEVSS_MEDIA_SERVER_NOTIFY_ON_PUSH_START}"
    MSNotifyOnPushStop: "${SKEYEVSS_MEDIA_SERVER_NOTIFY_ON_PUSH_STOP}"
    MSNotifyOnRelayPullStart: "${SKEYEVSS_MEDIA_SERVER_NOTIFY_ON_RELAY_PULL_START}"
    MSNotifyOnRelayPullStop: "${SKEYEVSS_MEDIA_SERVER_NOTIFY_ON_RELAY_PULL_STOP}"
    MSNotifyOnRtmpConnect: "${SKEYEVSS_MEDIA_SERVER_NOTIFY_ON_RTMP_CONNECT}"
    MSNotifyOnSubStart: "${SKEYEVSS_MEDIA_SERVER_NOTIFY_ON_SUB_START}"

    SSL:
        PublicKey: "${SKEYEVSS_SSL_CERT_PUBLIC_KEY}"
        PrivateKey: "${SKEYEVSS_SSL_CERT_PRIVATE_KEY}"

    Keys:
        MediaServer: "${SKEYEVSS_U_KEY_MEDIA_SERVER}"
        Vss: "${SKEYEVSS_U_KEY_VSS}"
        Cron: "${SKEYEVSS_U_KEY_CRON}"
        DB: "${SKEYEVSS_U_KEY_DB}"
        BackendApi: "${SKEYEVSS_U_KEY_BACKEND_API}"
        WebSev: "${SKEYEVSS_U_KEY_WEB_SEV}"

ConfigPath:
    # 配置文件
    WebSevConf: "${SKEYEVSS_WEB_SEV_CONF}"
    MediaServerGrpcConf: "${SKEYEVSS_MEDIA_SERVER_CONF}"
    VssGrpcConf: "${SKEYEVSS_VSS_GRPC_CONF}"
    VssConf: "${SKEYEVSS_VSS_CONF}"
    CronConf: "${SKEYEVSS_CRON_CONF}"
    DbGrpcConf: "${SKEYEVSS_DB_GRPC_CONF}"
    BackendApiConf: "${SKEYEVSS_BACKEND_API_CONF}"
    GuardConf: "${SKEYEVSS_GUARD_CONF}"

# 资源信息
SevRes:
    EntranceDir: "${SKEYEVSS_SEV_RES_ENTRANCE_DIR}"
    AssetDir: "${SKEYEVSS_SEV_RES_ASSET_DIR}"
    RedisAsset: "${SKEYEVSS_SEV_RES_REDIS_ASSET}"
    MysqlAsset: "${SKEYEVSS_SEV_RES_MYSQL_ASSET}"
    EtcdAsset: "${SKEYEVSS_SEV_RES_ETCD_ASSET}"
    FfmpegAsset: "${SKEYEVSS_SEV_RES_FFMPEG_ASSET}"
    BackendWebAsset: "${SKEYEVSS_SEV_RES_BACKEND_WEB_ASSET}"
    AppSevAsset: "${SKEYEVSS_SEV_RES_APP_SEV_ASSET}"
    EtcAsset: "${SKEYEVSS_SEV_RES_ETC_ASSET}"

    BackendWebCodePath: "${SKEYEVSS_BACKEND_WEB_CODE_PATH}"
    MediaServerCodePath: "${SKEYEVSS_MEDIA_SERVER_CODE_PATH}"
    GoPath: "${SKEYEVSS_GOPATH}"

    AssetScriptsDir: "${SKEYEVSS_SEV_RES_ASSET_SCRIPTS_DIR}"
    # 数据目录
    AssetCertDir: "${SKEYEVSS_SEV_RES_ASSET_CERT_DIR}"
    AssetDataDir: "${SKEYEVSS_SEV_RES_ASSET_DATA_DIR}"
    AssetDatalog: "${SKEYEVSS_SEV_RES_ASSET_DATA_LOG}"
    MysqlData: "${SKEYEVSS_SEV_RES_MYSQL_DATA}"
    RedisData: "${SKEYEVSS_SEV_RES_REDIS_DATA}"
    EtcdData: "${SKEYEVSS_SEV_RES_ETCD_DATA}"
    ApiDocDir: "${SKEYEVSS_SEV_RES_API_DIR}"

    UseMysql: ${SKEYEVSS_ENABLED_MYSQL}
    UseRedis: ${SKEYEVSS_ENABLED_REDIS}
    UseFfmpeg: ${SKEYEVSS_ENABLED_FFMPEG}
    UseEtcd: ${SKEYEVSS_ENABLED_ETCD}
    # mysql sqlite
    DatabaseType: "${SKEYEVSS_DATABASE_TYPE}"

    # 存放依赖服务配置文件
    ConfigDir: "${SKEYEVSS_SEV_RES_CONFIG_DIR}"
    MysqlConfigPath: "${SKEYEVSS_SEV_RES_MYSQL_CONFIG_PATH}"
    RedisConfigPath: "${SKEYEVSS_SEV_RES_REDIS_CONFIG_PATH}"
    EtcdConfigPath: "${SKEYEVSS_SEV_RES_ETCD_CONFIG_PATH}"

    DBBaseName: "${SKEYEVSS_MYSQL_DB_NAME_BASE}"
