// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: db.proto

package server

import (
	"context"

	"skeyevss/core/app/sev/db/db"
	"skeyevss/core/app/sev/db/internal/logic/backendservice"
	"skeyevss/core/app/sev/db/internal/svc"
)

type BackendServiceServer struct {
	svcCtx *svc.ServiceContext
	db.UnimplementedBackendServiceServer
}

func NewBackendServiceServer(svcCtx *svc.ServiceContext) *BackendServiceServer {
	return &BackendServiceServer{
		svcCtx: svcCtx,
	}
}

// 后台登录
func (s *BackendServiceServer) Login(ctx context.Context, in *db.LoginReq) (*db.Response, error) {
	l := backendservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 获取所有权限相关
func (s *BackendServiceServer) AuthRes(ctx context.Context, in *db.EmptyRequest) (*db.Response, error) {
	l := backendservicelogic.NewAuthResLogic(ctx, s.svcCtx)
	return l.AuthRes(in)
}

// 组织部门创建
func (s *BackendServiceServer) DepartmentCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := backendservicelogic.NewDepartmentCreateLogic(ctx, s.svcCtx)
	return l.DepartmentCreate(in)
}

// 组织部门删除
func (s *BackendServiceServer) DepartmentDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewDepartmentDeleteLogic(ctx, s.svcCtx)
	return l.DepartmentDelete(in)
}

// 组织部门修改
func (s *BackendServiceServer) DepartmentUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewDepartmentUpdateLogic(ctx, s.svcCtx)
	return l.DepartmentUpdate(in)
}

// 组织部门详情
func (s *BackendServiceServer) DepartmentRow(ctx context.Context, in *db.IDReq) (*db.Response, error) {
	l := backendservicelogic.NewDepartmentRowLogic(ctx, s.svcCtx)
	return l.DepartmentRow(in)
}

// 组织部门列表
func (s *BackendServiceServer) Departments(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewDepartmentsLogic(ctx, s.svcCtx)
	return l.Departments(in)
}

// 组织部门结构树
func (s *BackendServiceServer) DepartmentTrees(ctx context.Context, in *db.IdsReq) (*db.Response, error) {
	l := backendservicelogic.NewDepartmentTreesLogic(ctx, s.svcCtx)
	return l.DepartmentTrees(in)
}

// 角色创建
func (s *BackendServiceServer) RoleCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := backendservicelogic.NewRoleCreateLogic(ctx, s.svcCtx)
	return l.RoleCreate(in)
}

// 角色删除
func (s *BackendServiceServer) RoleDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewRoleDeleteLogic(ctx, s.svcCtx)
	return l.RoleDelete(in)
}

// 角色修改
func (s *BackendServiceServer) RoleUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewRoleUpdateLogic(ctx, s.svcCtx)
	return l.RoleUpdate(in)
}

// 角色详情
func (s *BackendServiceServer) RoleRow(ctx context.Context, in *db.IDReq) (*db.Response, error) {
	l := backendservicelogic.NewRoleRowLogic(ctx, s.svcCtx)
	return l.RoleRow(in)
}

// 角色列表
func (s *BackendServiceServer) Roles(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewRolesLogic(ctx, s.svcCtx)
	return l.Roles(in)
}

// 管理员创建
func (s *BackendServiceServer) AdminCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := backendservicelogic.NewAdminCreateLogic(ctx, s.svcCtx)
	return l.AdminCreate(in)
}

// 管理员删除
func (s *BackendServiceServer) AdminDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewAdminDeleteLogic(ctx, s.svcCtx)
	return l.AdminDelete(in)
}

// 管理员修改
func (s *BackendServiceServer) AdminUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewAdminUpdateLogic(ctx, s.svcCtx)
	return l.AdminUpdate(in)
}

// 管理员详情
func (s *BackendServiceServer) AdminRow(ctx context.Context, in *db.IDReq) (*db.Response, error) {
	l := backendservicelogic.NewAdminRowLogic(ctx, s.svcCtx)
	return l.AdminRow(in)
}

// 管理员列表
func (s *BackendServiceServer) Admins(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewAdminsLogic(ctx, s.svcCtx)
	return l.Admins(in)
}

// 更新密码
func (s *BackendServiceServer) AdminPassword(ctx context.Context, in *db.AdminPasswordReq) (*db.Response, error) {
	l := backendservicelogic.NewAdminPasswordLogic(ctx, s.svcCtx)
	return l.AdminPassword(in)
}

// 检查用户是否存在
func (s *BackendServiceServer) AdminCheckExists(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewAdminCheckExistsLogic(ctx, s.svcCtx)
	return l.AdminCheckExists(in)
}

// 初始化密码
func (s *BackendServiceServer) InitializeSetPassword(ctx context.Context, in *db.AdminPasswordReq) (*db.Response, error) {
	l := backendservicelogic.NewInitializeSetPasswordLogic(ctx, s.svcCtx)
	return l.InitializeSetPassword(in)
}

// 操作日志创建
func (s *BackendServiceServer) SystemOperationLogCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := backendservicelogic.NewSystemOperationLogCreateLogic(ctx, s.svcCtx)
	return l.SystemOperationLogCreate(in)
}

// 操作日志列表
func (s *BackendServiceServer) SystemOperationLogs(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := backendservicelogic.NewSystemOperationLogsLogic(ctx, s.svcCtx)
	return l.SystemOperationLogs(in)
}
