// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: db.proto

package configservice

import (
	"context"

	"skeyevss/core/app/sev/db/db"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminPasswordReq          = db.AdminPasswordReq
	DeviceChannelReq          = db.DeviceChannelReq
	EmptyRequest              = db.EmptyRequest
	IDReq                     = db.IDReq
	IdsReq                    = db.IdsReq
	LoginReq                  = db.LoginReq
	MapReq                    = db.MapReq
	PermissionItem            = db.PermissionItem
	PermissionResourceInitReq = db.PermissionResourceInitReq
	Response                  = db.Response
	SliceMapReq               = db.SliceMapReq
	TypeReq                   = db.TypeReq
	UniqueIdReq               = db.UniqueIdReq
	UniqueIdsReq              = db.UniqueIdsReq
	XConditionItem            = db.XConditionItem
	XConditionOriginalItem    = db.XConditionOriginalItem
	XOrderItem                = db.XOrderItem
	XRequestParams            = db.XRequestParams
	XResponse                 = db.XResponse
	XUpdateItem               = db.XUpdateItem

	ConfigService interface {
		// 获取uniqueId
		MaxId(ctx context.Context, in *TypeReq, opts ...grpc.CallOption) (*Response, error)
		// 字典创建
		DictionaryCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 字典删除
		DictionaryDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 字典更新
		DictionaryUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 管理员详情
		DictionaryRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error)
		// 字典列表
		Dictionaries(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 字典结构树
		DictionaryTrees(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error)
		// 字典检查uniqueId是否存在
		DictionaryCheckUniqueId(ctx context.Context, in *UniqueIdReq, opts ...grpc.CallOption) (*Response, error)
		// 设置更新
		SettingUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 设置获取
		SettingRow(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error)
		// 任务创建
		CrontabCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 任务删除
		CrontabDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 任务更新
		CrontabUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 任务批量更新
		CrontabBulkUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 任务详情
		CrontabRow(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 任务列表
		CrontabList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 所有数据
		Crontab(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error)
		// media server创建
		MsCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// media server删除
		MsDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// media server更新
		MsUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// media server详情
		MsRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error)
		// media server列表
		MsList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// media server option 列表
		MsOptions(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error)
		// 录像计划创建
		VideoProjectCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 录像计划删除
		VideoProjectDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 录像计划更新
		VideoProjectUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 录像计划详情
		VideoProjectRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error)
		// 录像计划列表
		VideoProjectList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
	}

	defaultConfigService struct {
		cli zrpc.Client
	}
)

func NewConfigService(cli zrpc.Client) ConfigService {
	return &defaultConfigService{
		cli: cli,
	}
}

// 获取uniqueId
func (m *defaultConfigService) MaxId(ctx context.Context, in *TypeReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.MaxId(ctx, in, opts...)
}

// 字典创建
func (m *defaultConfigService) DictionaryCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.DictionaryCreate(ctx, in, opts...)
}

// 字典删除
func (m *defaultConfigService) DictionaryDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.DictionaryDelete(ctx, in, opts...)
}

// 字典更新
func (m *defaultConfigService) DictionaryUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.DictionaryUpdate(ctx, in, opts...)
}

// 管理员详情
func (m *defaultConfigService) DictionaryRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.DictionaryRow(ctx, in, opts...)
}

// 字典列表
func (m *defaultConfigService) Dictionaries(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.Dictionaries(ctx, in, opts...)
}

// 字典结构树
func (m *defaultConfigService) DictionaryTrees(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.DictionaryTrees(ctx, in, opts...)
}

// 字典检查uniqueId是否存在
func (m *defaultConfigService) DictionaryCheckUniqueId(ctx context.Context, in *UniqueIdReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.DictionaryCheckUniqueId(ctx, in, opts...)
}

// 设置更新
func (m *defaultConfigService) SettingUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.SettingUpdate(ctx, in, opts...)
}

// 设置获取
func (m *defaultConfigService) SettingRow(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.SettingRow(ctx, in, opts...)
}

// 任务创建
func (m *defaultConfigService) CrontabCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.CrontabCreate(ctx, in, opts...)
}

// 任务删除
func (m *defaultConfigService) CrontabDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.CrontabDelete(ctx, in, opts...)
}

// 任务更新
func (m *defaultConfigService) CrontabUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.CrontabUpdate(ctx, in, opts...)
}

// 任务批量更新
func (m *defaultConfigService) CrontabBulkUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.CrontabBulkUpdate(ctx, in, opts...)
}

// 任务详情
func (m *defaultConfigService) CrontabRow(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.CrontabRow(ctx, in, opts...)
}

// 任务列表
func (m *defaultConfigService) CrontabList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.CrontabList(ctx, in, opts...)
}

// 所有数据
func (m *defaultConfigService) Crontab(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.Crontab(ctx, in, opts...)
}

// media server创建
func (m *defaultConfigService) MsCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.MsCreate(ctx, in, opts...)
}

// media server删除
func (m *defaultConfigService) MsDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.MsDelete(ctx, in, opts...)
}

// media server更新
func (m *defaultConfigService) MsUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.MsUpdate(ctx, in, opts...)
}

// media server详情
func (m *defaultConfigService) MsRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.MsRow(ctx, in, opts...)
}

// media server列表
func (m *defaultConfigService) MsList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.MsList(ctx, in, opts...)
}

// media server option 列表
func (m *defaultConfigService) MsOptions(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.MsOptions(ctx, in, opts...)
}

// 录像计划创建
func (m *defaultConfigService) VideoProjectCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.VideoProjectCreate(ctx, in, opts...)
}

// 录像计划删除
func (m *defaultConfigService) VideoProjectDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.VideoProjectDelete(ctx, in, opts...)
}

// 录像计划更新
func (m *defaultConfigService) VideoProjectUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.VideoProjectUpdate(ctx, in, opts...)
}

// 录像计划详情
func (m *defaultConfigService) VideoProjectRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.VideoProjectRow(ctx, in, opts...)
}

// 录像计划列表
func (m *defaultConfigService) VideoProjectList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewConfigServiceClient(m.cli.Conn())
	return client.VideoProjectList(ctx, in, opts...)
}
