// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: db.proto

package server

import (
	"context"

	"skeyevss/core/app/sev/db/db"
	"skeyevss/core/app/sev/db/internal/logic/deviceservice"
	"skeyevss/core/app/sev/db/internal/svc"
)

type DeviceServiceServer struct {
	svcCtx *svc.ServiceContext
	db.UnimplementedDeviceServiceServer
}

func NewDeviceServiceServer(svcCtx *svc.ServiceContext) *DeviceServiceServer {
	return &DeviceServiceServer{
		svcCtx: svcCtx,
	}
}

// 设备在线状态 type = 1 设备 2 通道
func (s *DeviceServiceServer) OnlineState(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewOnlineStateLogic(ctx, s.svcCtx)
	return l.OnlineState(in)
}

// rtsp stream url 分组 accessProtocol
func (s *DeviceServiceServer) RtspStreamGroups(ctx context.Context, in *db.IdsReq) (*db.Response, error) {
	l := deviceservicelogic.NewRtspStreamGroupsLogic(ctx, s.svcCtx)
	return l.RtspStreamGroups(in)
}

// 设备创建
func (s *DeviceServiceServer) DeviceCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := deviceservicelogic.NewDeviceCreateLogic(ctx, s.svcCtx)
	return l.DeviceCreate(in)
}

// 设备upsert
func (s *DeviceServiceServer) DeviceUpsert(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := deviceservicelogic.NewDeviceUpsertLogic(ctx, s.svcCtx)
	return l.DeviceUpsert(in)
}

// 设备删除
func (s *DeviceServiceServer) DeviceDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewDeviceDeleteLogic(ctx, s.svcCtx)
	return l.DeviceDelete(in)
}

// 设备更新
func (s *DeviceServiceServer) DeviceUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewDeviceUpdateLogic(ctx, s.svcCtx)
	return l.DeviceUpdate(in)
}

// 设备详情
func (s *DeviceServiceServer) DeviceRow(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewDeviceRowLogic(ctx, s.svcCtx)
	return l.DeviceRow(in)
}

// 设备列表
func (s *DeviceServiceServer) DeviceList(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewDeviceListLogic(ctx, s.svcCtx)
	return l.DeviceList(in)
}

// 通道创建
func (s *DeviceServiceServer) ChannelCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := deviceservicelogic.NewChannelCreateLogic(ctx, s.svcCtx)
	return l.ChannelCreate(in)
}

// 通道upsert
func (s *DeviceServiceServer) ChannelUpsert(ctx context.Context, in *db.SliceMapReq) (*db.Response, error) {
	l := deviceservicelogic.NewChannelUpsertLogic(ctx, s.svcCtx)
	return l.ChannelUpsert(in)
}

// 通道upsert
func (s *DeviceServiceServer) ChannelCascadeUpsert(ctx context.Context, in *db.SliceMapReq) (*db.Response, error) {
	l := deviceservicelogic.NewChannelCascadeUpsertLogic(ctx, s.svcCtx)
	return l.ChannelCascadeUpsert(in)
}

// 通道删除
func (s *DeviceServiceServer) ChannelDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewChannelDeleteLogic(ctx, s.svcCtx)
	return l.ChannelDelete(in)
}

// 通道更新
func (s *DeviceServiceServer) ChannelUpdate(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewChannelUpdateLogic(ctx, s.svcCtx)
	return l.ChannelUpdate(in)
}

// 通道详情
func (s *DeviceServiceServer) ChannelRow(ctx context.Context, in *db.IDReq) (*db.Response, error) {
	l := deviceservicelogic.NewChannelRowLogic(ctx, s.svcCtx)
	return l.ChannelRow(in)
}

// 通道详情
func (s *DeviceServiceServer) ChannelRowFind(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewChannelRowFindLogic(ctx, s.svcCtx)
	return l.ChannelRowFind(in)
}

// 通道列表
func (s *DeviceServiceServer) ChannelList(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewChannelListLogic(ctx, s.svcCtx)
	return l.ChannelList(in)
}

// 通道数量
func (s *DeviceServiceServer) ChannelTotal(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewChannelTotalLogic(ctx, s.svcCtx)
	return l.ChannelTotal(in)
}

// 通道列表
func (s *DeviceServiceServer) ChannelXlist(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewChannelXlistLogic(ctx, s.svcCtx)
	return l.ChannelXlist(in)
}

// 获取通道媒体服务id
func (s *DeviceServiceServer) MediaServersWithChannelIds(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewMediaServersWithChannelIdsLogic(ctx, s.svcCtx)
	return l.MediaServersWithChannelIds(in)
}

// 检测通道是否存在
func (s *DeviceServiceServer) ChannelExists(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewChannelExistsLogic(ctx, s.svcCtx)
	return l.ChannelExists(in)
}

// 删除通道(Devices.ChannelFilters)
func (s *DeviceServiceServer) ChannelDeleteWithChannelFilters(ctx context.Context, in *db.UniqueIdsReq) (*db.Response, error) {
	l := deviceservicelogic.NewChannelDeleteWithChannelFiltersLogic(ctx, s.svcCtx)
	return l.ChannelDeleteWithChannelFilters(in)
}

// 设备通道列表(通过通道id获取)
func (s *DeviceServiceServer) DeviceChannelRelationsWithChannelIds(ctx context.Context, in *db.UniqueIdsReq) (*db.Response, error) {
	l := deviceservicelogic.NewDeviceChannelRelationsWithChannelIdsLogic(ctx, s.svcCtx)
	return l.DeviceChannelRelationsWithChannelIds(in)
}

// 设备通道信息
func (s *DeviceServiceServer) DeviceChannel(ctx context.Context, in *db.DeviceChannelReq) (*db.Response, error) {
	l := deviceservicelogic.NewDeviceChannelLogic(ctx, s.svcCtx)
	return l.DeviceChannel(in)
}

// 设备在线统计
func (s *DeviceServiceServer) DeviceOnlineStatistics(ctx context.Context, in *db.EmptyRequest) (*db.Response, error) {
	l := deviceservicelogic.NewDeviceOnlineStatisticsLogic(ctx, s.svcCtx)
	return l.DeviceOnlineStatistics(in)
}

// 报警创建
func (s *DeviceServiceServer) AlarmCreate(ctx context.Context, in *db.MapReq) (*db.Response, error) {
	l := deviceservicelogic.NewAlarmCreateLogic(ctx, s.svcCtx)
	return l.AlarmCreate(in)
}

// 报警删除
func (s *DeviceServiceServer) AlarmDelete(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewAlarmDeleteLogic(ctx, s.svcCtx)
	return l.AlarmDelete(in)
}

// 报警列表
func (s *DeviceServiceServer) AlarmList(ctx context.Context, in *db.XRequestParams) (*db.Response, error) {
	l := deviceservicelogic.NewAlarmListLogic(ctx, s.svcCtx)
	return l.AlarmList(in)
}
