// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: db.proto

package deviceservice

import (
	"context"

	"skeyevss/core/app/sev/db/db"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminPasswordReq          = db.AdminPasswordReq
	DeviceChannelReq          = db.DeviceChannelReq
	EmptyRequest              = db.EmptyRequest
	IDReq                     = db.IDReq
	IdsReq                    = db.IdsReq
	LoginReq                  = db.LoginReq
	MapReq                    = db.MapReq
	PermissionItem            = db.PermissionItem
	PermissionResourceInitReq = db.PermissionResourceInitReq
	Response                  = db.Response
	SliceMapReq               = db.SliceMapReq
	TypeReq                   = db.TypeReq
	UniqueIdReq               = db.UniqueIdReq
	UniqueIdsReq              = db.UniqueIdsReq
	XConditionItem            = db.XConditionItem
	XConditionOriginalItem    = db.XConditionOriginalItem
	XOrderItem                = db.XOrderItem
	XRequestParams            = db.XRequestParams
	XResponse                 = db.XResponse
	XUpdateItem               = db.XUpdateItem

	DeviceService interface {
		// 设备在线状态 type = 1 设备 2 通道
		OnlineState(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// rtsp stream url 分组 accessProtocol
		RtspStreamGroups(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*Response, error)
		// 设备创建
		DeviceCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 设备upsert
		DeviceUpsert(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 设备删除
		DeviceDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 设备更新
		DeviceUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 设备详情
		DeviceRow(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 设备列表
		DeviceList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 通道创建
		ChannelCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 通道upsert
		ChannelUpsert(ctx context.Context, in *SliceMapReq, opts ...grpc.CallOption) (*Response, error)
		// 通道upsert
		ChannelCascadeUpsert(ctx context.Context, in *SliceMapReq, opts ...grpc.CallOption) (*Response, error)
		// 通道删除
		ChannelDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 通道更新
		ChannelUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 通道详情
		ChannelRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error)
		// 通道详情
		ChannelRowFind(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 通道列表
		ChannelList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 通道数量
		ChannelTotal(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 通道列表
		ChannelXlist(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 获取通道媒体服务id
		MediaServersWithChannelIds(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 检测通道是否存在
		ChannelExists(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 删除通道(Devices.ChannelFilters)
		ChannelDeleteWithChannelFilters(ctx context.Context, in *UniqueIdsReq, opts ...grpc.CallOption) (*Response, error)
		// 设备通道列表(通过通道id获取)
		DeviceChannelRelationsWithChannelIds(ctx context.Context, in *UniqueIdsReq, opts ...grpc.CallOption) (*Response, error)
		// 设备通道信息
		DeviceChannel(ctx context.Context, in *DeviceChannelReq, opts ...grpc.CallOption) (*Response, error)
		// 设备在线统计
		DeviceOnlineStatistics(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error)
		// 报警创建
		AlarmCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error)
		// 报警删除
		AlarmDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
		// 报警列表
		AlarmList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error)
	}

	defaultDeviceService struct {
		cli zrpc.Client
	}
)

func NewDeviceService(cli zrpc.Client) DeviceService {
	return &defaultDeviceService{
		cli: cli,
	}
}

// 设备在线状态 type = 1 设备 2 通道
func (m *defaultDeviceService) OnlineState(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.OnlineState(ctx, in, opts...)
}

// rtsp stream url 分组 accessProtocol
func (m *defaultDeviceService) RtspStreamGroups(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.RtspStreamGroups(ctx, in, opts...)
}

// 设备创建
func (m *defaultDeviceService) DeviceCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.DeviceCreate(ctx, in, opts...)
}

// 设备upsert
func (m *defaultDeviceService) DeviceUpsert(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.DeviceUpsert(ctx, in, opts...)
}

// 设备删除
func (m *defaultDeviceService) DeviceDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.DeviceDelete(ctx, in, opts...)
}

// 设备更新
func (m *defaultDeviceService) DeviceUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.DeviceUpdate(ctx, in, opts...)
}

// 设备详情
func (m *defaultDeviceService) DeviceRow(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.DeviceRow(ctx, in, opts...)
}

// 设备列表
func (m *defaultDeviceService) DeviceList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.DeviceList(ctx, in, opts...)
}

// 通道创建
func (m *defaultDeviceService) ChannelCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelCreate(ctx, in, opts...)
}

// 通道upsert
func (m *defaultDeviceService) ChannelUpsert(ctx context.Context, in *SliceMapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelUpsert(ctx, in, opts...)
}

// 通道upsert
func (m *defaultDeviceService) ChannelCascadeUpsert(ctx context.Context, in *SliceMapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelCascadeUpsert(ctx, in, opts...)
}

// 通道删除
func (m *defaultDeviceService) ChannelDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelDelete(ctx, in, opts...)
}

// 通道更新
func (m *defaultDeviceService) ChannelUpdate(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelUpdate(ctx, in, opts...)
}

// 通道详情
func (m *defaultDeviceService) ChannelRow(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelRow(ctx, in, opts...)
}

// 通道详情
func (m *defaultDeviceService) ChannelRowFind(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelRowFind(ctx, in, opts...)
}

// 通道列表
func (m *defaultDeviceService) ChannelList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelList(ctx, in, opts...)
}

// 通道数量
func (m *defaultDeviceService) ChannelTotal(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelTotal(ctx, in, opts...)
}

// 通道列表
func (m *defaultDeviceService) ChannelXlist(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelXlist(ctx, in, opts...)
}

// 获取通道媒体服务id
func (m *defaultDeviceService) MediaServersWithChannelIds(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.MediaServersWithChannelIds(ctx, in, opts...)
}

// 检测通道是否存在
func (m *defaultDeviceService) ChannelExists(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelExists(ctx, in, opts...)
}

// 删除通道(Devices.ChannelFilters)
func (m *defaultDeviceService) ChannelDeleteWithChannelFilters(ctx context.Context, in *UniqueIdsReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.ChannelDeleteWithChannelFilters(ctx, in, opts...)
}

// 设备通道列表(通过通道id获取)
func (m *defaultDeviceService) DeviceChannelRelationsWithChannelIds(ctx context.Context, in *UniqueIdsReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.DeviceChannelRelationsWithChannelIds(ctx, in, opts...)
}

// 设备通道信息
func (m *defaultDeviceService) DeviceChannel(ctx context.Context, in *DeviceChannelReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.DeviceChannel(ctx, in, opts...)
}

// 设备在线统计
func (m *defaultDeviceService) DeviceOnlineStatistics(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.DeviceOnlineStatistics(ctx, in, opts...)
}

// 报警创建
func (m *defaultDeviceService) AlarmCreate(ctx context.Context, in *MapReq, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.AlarmCreate(ctx, in, opts...)
}

// 报警删除
func (m *defaultDeviceService) AlarmDelete(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.AlarmDelete(ctx, in, opts...)
}

// 报警列表
func (m *defaultDeviceService) AlarmList(ctx context.Context, in *XRequestParams, opts ...grpc.CallOption) (*Response, error) {
	client := db.NewDeviceServiceClient(m.cli.Conn())
	return client.AlarmList(ctx, in, opts...)
}
