// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	configcrontab "skeyevss/core/app/sev/backend/internal/handler/config/crontab"
	configdictionaries "skeyevss/core/app/sev/backend/internal/handler/config/dictionaries"
	configenv "skeyevss/core/app/sev/backend/internal/handler/config/env"
	configms "skeyevss/core/app/sev/backend/internal/handler/config/ms"
	configsetting "skeyevss/core/app/sev/backend/internal/handler/config/setting"
	configvp "skeyevss/core/app/sev/backend/internal/handler/config/vp"
	devicealarms "skeyevss/core/app/sev/backend/internal/handler/device/alarms"
	devicechannels "skeyevss/core/app/sev/backend/internal/handler/device/channels"
	deviceitems "skeyevss/core/app/sev/backend/internal/handler/device/items"
	internalCall "skeyevss/core/app/sev/backend/internal/handler/internalCall"
	login "skeyevss/core/app/sev/backend/internal/handler/login"
	logs "skeyevss/core/app/sev/backend/internal/handler/logs"
	systemadmins "skeyevss/core/app/sev/backend/internal/handler/system/admins"
	systemdepartments "skeyevss/core/app/sev/backend/internal/handler/system/departments"
	systemroles "skeyevss/core/app/sev/backend/internal/handler/system/roles"
	systemserver "skeyevss/core/app/sev/backend/internal/handler/system/server"
	tool "skeyevss/core/app/sev/backend/internal/handler/tool"
	user "skeyevss/core/app/sev/backend/internal/handler/user"
	videosdevices "skeyevss/core/app/sev/backend/internal/handler/videos/devices"
	videossk "skeyevss/core/app/sev/backend/internal/handler/videos/sk"
	"skeyevss/core/app/sev/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建
					Method:  http.MethodPost,
					Path:    "/crontab",
					Handler: configcrontab.CreateHandler(serverCtx),
				},
				{
					// 更新
					Method:  http.MethodPut,
					Path:    "/crontab",
					Handler: configcrontab.UpdateHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/crontab",
					Handler: configcrontab.DeleteHandler(serverCtx),
				},
				{
					// 详情
					Method:  http.MethodGet,
					Path:    "/crontab/:uniqueId",
					Handler: configcrontab.RowHandler(serverCtx),
				},
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/crontab/list",
					Handler: configcrontab.ListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建字典
					Method:  http.MethodPost,
					Path:    "/dictionaries",
					Handler: configdictionaries.CreateHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/dictionaries",
					Handler: configdictionaries.DeleteHandler(serverCtx),
				},
				{
					// 更新字典
					Method:  http.MethodPut,
					Path:    "/dictionary",
					Handler: configdictionaries.UpdateHandler(serverCtx),
				},
				{
					// 字典详情
					Method:  http.MethodGet,
					Path:    "/dictionary/:id",
					Handler: configdictionaries.RowHandler(serverCtx),
				},
				{
					// 检查uniqueId
					Method:  http.MethodGet,
					Path:    "/dictionary/check/:uniqueId",
					Handler: configdictionaries.CheckUniqueIdHandler(serverCtx),
				},
				{
					// 字典列表
					Method:  http.MethodPost,
					Path:    "/dictionary/list",
					Handler: configdictionaries.ListHandler(serverCtx),
				},
				{
					// 字典结构树
					Method:  http.MethodGet,
					Path:    "/dictionary/trees",
					Handler: configdictionaries.TreesHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 更新
					Method:  http.MethodPut,
					Path:    "/env",
					Handler: configenv.UpdateHandler(serverCtx),
				},
				{
					// 详情
					Method:  http.MethodGet,
					Path:    "/env",
					Handler: configenv.RowHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建
					Method:  http.MethodPost,
					Path:    "/ms",
					Handler: configms.CreateHandler(serverCtx),
				},
				{
					// 更新
					Method:  http.MethodPut,
					Path:    "/ms",
					Handler: configms.UpdateHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/ms",
					Handler: configms.DeleteHandler(serverCtx),
				},
				{
					// options
					Method:  http.MethodGet,
					Path:    "/ms-options",
					Handler: configms.OptionsHandler(serverCtx),
				},
				{
					// 详情
					Method:  http.MethodGet,
					Path:    "/ms/:id",
					Handler: configms.RowHandler(serverCtx),
				},
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/ms/list",
					Handler: configms.ListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 系统设置
					Method:  http.MethodGet,
					Path:    "/setting",
					Handler: configsetting.SettingHandler(serverCtx),
				},
				{
					// 更新
					Method:  http.MethodPut,
					Path:    "/setting",
					Handler: configsetting.UpdateHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.BaseMiddleware},
			[]rest.Route{
				{
					// 系统设置
					Method:  http.MethodGet,
					Path:    "/conf",
					Handler: configsetting.ConfHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建
					Method:  http.MethodPost,
					Path:    "/video-project",
					Handler: configvp.CreateHandler(serverCtx),
				},
				{
					// 更新
					Method:  http.MethodPut,
					Path:    "/video-project",
					Handler: configvp.UpdateHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/video-project",
					Handler: configvp.DeleteHandler(serverCtx),
				},
				{
					// 详情
					Method:  http.MethodGet,
					Path:    "/video-project/:id",
					Handler: configvp.RowHandler(serverCtx),
				},
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/video-project/list",
					Handler: configvp.ListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/device/alarm",
					Handler: devicealarms.DeleteHandler(serverCtx),
				},
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/device/alarm/list",
					Handler: devicealarms.ListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建
					Method:  http.MethodPost,
					Path:    "/device/channel",
					Handler: devicechannels.CreateHandler(serverCtx),
				},
				{
					// 更新
					Method:  http.MethodPut,
					Path:    "/device/channel",
					Handler: devicechannels.UpdateHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/device/channel",
					Handler: devicechannels.DeleteHandler(serverCtx),
				},
				{
					// 详情条件获取
					Method:  http.MethodPost,
					Path:    "/device/channel-with-params",
					Handler: devicechannels.RowWithReqHandler(serverCtx),
				},
				{
					// 详情
					Method:  http.MethodGet,
					Path:    "/device/channel/:id",
					Handler: devicechannels.RowHandler(serverCtx),
				},
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/device/channel/list",
					Handler: devicechannels.ListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建
					Method:  http.MethodPost,
					Path:    "/device/item",
					Handler: deviceitems.CreateHandler(serverCtx),
				},
				{
					// 更新
					Method:  http.MethodPut,
					Path:    "/device/item",
					Handler: deviceitems.UpdateHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/device/item",
					Handler: deviceitems.DeleteHandler(serverCtx),
				},
				{
					// 详情uniqueId
					Method:  http.MethodGet,
					Path:    "/device/item-u/:uniqueId",
					Handler: deviceitems.RowWithUniqueIdHandler(serverCtx),
				},
				{
					// 详情
					Method:  http.MethodGet,
					Path:    "/device/item/:id",
					Handler: deviceitems.RowHandler(serverCtx),
				},
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/device/item/list",
					Handler: deviceitems.ListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 获取所有流组信息
					Method:  http.MethodPost,
					Path:    "/internal/ms/all-groups",
					Handler: internalCall.MSAllGroupsHandler(serverCtx),
				},
				{
					// 获取流媒体服务简略配置信息
					Method:  http.MethodPost,
					Path:    "/internal/ms/config",
					Handler: internalCall.MSConfigBriefHandler(serverCtx),
				},
				{
					// 按录像流名称列表查询服务录像
					Method:  http.MethodPost,
					Path:    "/internal/ms/query-record-by-names",
					Handler: internalCall.MSQueryRecordByNamesHandler(serverCtx),
				},
				{
					// 设置流媒体服务重要配置参数并重启服务
					Method:  http.MethodPost,
					Path:    "/internal/ms/reload",
					Handler: internalCall.MSReloadHandler(serverCtx),
				},
				{
					// 设备控制
					Method:  http.MethodPost,
					Path:    "/internal/vss/device-control",
					Handler: internalCall.DeviceControlHandler(serverCtx),
				},
				{
					// gbc发送catalog请求
					Method:  http.MethodPost,
					Path:    "/internal/vss/gbc/catalog",
					Handler: internalCall.GBCCatalogHandler(serverCtx),
				},
				{
					// gbs发送catalog请求
					Method:  http.MethodGet,
					Path:    "/internal/vss/gbs/catalog/:deviceUniqueId",
					Handler: internalCall.GBSCatalogHandler(serverCtx),
				},
				{
					// 视频回放控制
					Method:  http.MethodPost,
					Path:    "/internal/vss/gbs/playback-control",
					Handler: internalCall.PlaybackControlHandler(serverCtx),
				},
				{
					// 获取设备信息
					Method:  http.MethodPost,
					Path:    "/internal/vss/onvif/device-info",
					Handler: internalCall.OnvifDeviceInfoHandler(serverCtx),
				},
				{
					// 探测设备
					Method:  http.MethodGet,
					Path:    "/internal/vss/onvif/discover",
					Handler: internalCall.OnvifDiscoverHandler(serverCtx),
				},
				{
					// 设置预设位
					Method:  http.MethodPost,
					Path:    "/internal/vss/preset-point",
					Handler: internalCall.PresetPointHandler(serverCtx),
				},
				{
					// 获取预设位
					Method:  http.MethodPost,
					Path:    "/internal/vss/preset-points",
					Handler: internalCall.PresetPointsHandler(serverCtx),
				},
				{
					// 停止流
					Method:  http.MethodPost,
					Path:    "/internal/vss/video/stop",
					Handler: internalCall.VideoStreamStopHandler(serverCtx),
				},
				{
					// 视频播放获取播放地址
					Method:  http.MethodPost,
					Path:    "/internal/vss/video/stream",
					Handler: internalCall.VideoStreamHandler(serverCtx),
				},
				{
					// 获取流信息
					Method:  http.MethodGet,
					Path:    "/internal/vss/video/stream/:id/:streamName",
					Handler: internalCall.VideoStreamQueryHandler(serverCtx),
				},
				{
					// ws token
					Method:  http.MethodGet,
					Path:    "/internal/vss/ws-token",
					Handler: internalCall.WSTokenHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.BaseMiddleware},
			[]rest.Route{
				{
					// 用户名登录
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: login.LoginHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 运行日志
					Method:  http.MethodGet,
					Path:    "/run-logs",
					Handler: logs.RunLogsHandler(serverCtx),
				},
				{
					// 查看日志
					Method:  http.MethodGet,
					Path:    "/run-logs/:page/:pageSize/:fileName",
					Handler: logs.CatLogHandler(serverCtx),
				},
				{
					// sip日志
					Method:  http.MethodGet,
					Path:    "/sip-logs/:page/:pageSize/:fileName",
					Handler: logs.SipLogHandler(serverCtx),
				},
				{
					// 操作日志列表
					Method:  http.MethodPost,
					Path:    "/system-operation-logs",
					Handler: logs.SystemOperationLogsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 更新管理员
					Method:  http.MethodPut,
					Path:    "/admin",
					Handler: systemadmins.UpdateHandler(serverCtx),
				},
				{
					// 管理员详情
					Method:  http.MethodGet,
					Path:    "/admin/:id",
					Handler: systemadmins.RowHandler(serverCtx),
				},
				{
					// 检查用户是否存在
					Method:  http.MethodPost,
					Path:    "/admin/exists",
					Handler: systemadmins.ExistsHandler(serverCtx),
				},
				{
					// 管理员列表
					Method:  http.MethodPost,
					Path:    "/admin/list",
					Handler: systemadmins.ListHandler(serverCtx),
				},
				{
					// 创建管理员
					Method:  http.MethodPost,
					Path:    "/admins",
					Handler: systemadmins.CreateHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/admins",
					Handler: systemadmins.DeleteHandler(serverCtx),
				},
				{
					// 更新初始密码
					Method:  http.MethodPut,
					Path:    "/initialize-password",
					Handler: systemadmins.InitializeSetPasswordHandler(serverCtx),
				},
				{
					// 更新密码
					Method:  http.MethodPut,
					Path:    "/password",
					Handler: systemadmins.SetPasswordHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 更新
					Method:  http.MethodPut,
					Path:    "/department",
					Handler: systemdepartments.UpdateHandler(serverCtx),
				},
				{
					// 详情
					Method:  http.MethodGet,
					Path:    "/department/:id",
					Handler: systemdepartments.RowHandler(serverCtx),
				},
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/department/list",
					Handler: systemdepartments.ListHandler(serverCtx),
				},
				{
					// 结构树
					Method:  http.MethodGet,
					Path:    "/department/trees",
					Handler: systemdepartments.TreesHandler(serverCtx),
				},
				{
					// 创建
					Method:  http.MethodPost,
					Path:    "/departments",
					Handler: systemdepartments.CreateHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/departments",
					Handler: systemdepartments.DeleteHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 更新角色
					Method:  http.MethodPut,
					Path:    "/role",
					Handler: systemroles.UpdateHandler(serverCtx),
				},
				{
					// 角色详情
					Method:  http.MethodGet,
					Path:    "/role/:id",
					Handler: systemroles.RowHandler(serverCtx),
				},
				{
					// 角色列表
					Method:  http.MethodPost,
					Path:    "/role/list",
					Handler: systemroles.ListHandler(serverCtx),
				},
				{
					// 创建角色
					Method:  http.MethodPost,
					Path:    "/roles",
					Handler: systemroles.CreateHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/roles",
					Handler: systemroles.DeleteHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 获取uniqueId
					Method:  http.MethodPost,
					Path:    "/gen-uniqueId",
					Handler: systemserver.GenUniqueIdHandler(serverCtx),
				},
				{
					// 性能分析
					Method:  http.MethodPost,
					Path:    "/pprof-analyze",
					Handler: systemserver.PProfAnalyzeHandler(serverCtx),
				},
				{
					// 响应查询
					Method:  http.MethodPost,
					Path:    "/resp-query",
					Handler: systemserver.RespQueryHandler(serverCtx),
				},
				{
					// 健康检查
					Method:  http.MethodGet,
					Path:    "/server-health",
					Handler: systemserver.HealthHandler(serverCtx),
				},
				{
					// 系统信息
					Method:  http.MethodGet,
					Path:    "/system-info",
					Handler: systemserver.SystemInfoHandler(serverCtx),
				},
				{
					// 重启服务
					Method:  http.MethodGet,
					Path:    "/system-restart",
					Handler: systemserver.ServerRestartHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.BaseMiddleware},
			[]rest.Route{
				{
					// base64 文件上传
					Method:  http.MethodPost,
					Path:    "/file/base64",
					Handler: tool.UploadBase64FileHandler(serverCtx),
				},
				{
					// 文件上传
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: tool.UploadFileHandler(serverCtx),
				},
				{
					// mac地址
					Method:  http.MethodGet,
					Path:    "/mac",
					Handler: tool.MACHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/tool"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 用户信息
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: user.InfoHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/video/devices",
					Handler: videosdevices.ListHandler(serverCtx),
				},
				{
					// 下载
					Method:  http.MethodPost,
					Path:    "/video/devices/download",
					Handler: videosdevices.DownloadHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/video/sk",
					Handler: videossk.ListHandler(serverCtx),
				},
				{
					// 删除
					Method:  http.MethodDelete,
					Path:    "/video/sk",
					Handler: videossk.DeleteHandler(serverCtx),
				},
				{
					// 时间检测
					Method:  http.MethodPost,
					Path:    "/video/sk-date-contains",
					Handler: videossk.DateContainsHandler(serverCtx),
				},
				{
					// 获取指定时间录像
					Method:  http.MethodPost,
					Path:    "/video/sk/find-with-time",
					Handler: videossk.FindWithTimeHandler(serverCtx),
				},
			}...,
		),
	)
}
