// Code generated by goctl. DO NOT EDIT.
package types

type ActivateCodeReq struct {
	Code string `json:"code"`
}

type Base64FileUploadReq struct {
	Stream string `json:"stream"`
}

type BulkUpdateInner struct {
	PK   interface{} `json:"pk"`            // 主键值
	Val  interface{} `json:"val"`           // 更新内容
	Type int64       `json:"type,optional"` // 更新方式 0 ?占位符 1 原始数据
}

type CodeReq struct {
	Code string `json:"code"`
}

type ConditionItem struct {
	Column          string                 `json:"column"`
	Value           interface{}            `json:"value"`
	Values          []interface{}          `json:"values"`
	Operator        string                 `json:"operator"`
	UseNil          bool                   `json:"-"`
	Original        *ConditionOriginalItem `json:"-"`
	LogicalOperator string                 `json:"logicalOperator"`
	Inner           []*ConditionItem       `json:"inner"`
	Columns         []string               `json:"-"`
}

type ConditionOriginalItem struct {
	Query  string
	Values []interface{}
}

type DCReq struct {
	ChannelUniqueId string `json:"channelUniqueId,optional"`
	DeviceUniqueId  string `json:"deviceUniqueId,optional"`
	MsID            uint64 `json:"msID,optional"`
}

type DeviceUniqueIdReq struct {
	DeviceUniqueId string `path:"deviceUniqueId"`
}

type FileNameQuery struct {
	FileName string `path:"fileName"`
	Page     int    `path:"page"`
	PageSize int    `path:"pageSize"`
}

type GenUniqueIdReq struct {
	Type  string `json:"type"`
	Count int    `json:"count"`
}

type IdQuery struct {
	Id uint `path:"id"`
}

type InitializeSetPasswordReq struct {
	Password string `json:"password"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Remember bool   `json:"remember,optional"`
}

type MSConfigReq struct {
	IP   string `json:"ip"`
	Port int    `json:"port"`
}

type MsQueryRecordByNameReq struct {
	StreamNames     []string `json:"streamNames"`
	RecordType      uint     `json:"recordType"`
	ChannelUniqueId string   `json:"channelUniqueId,optional"`
	DeviceUniqueId  string   `json:"deviceUniqueId,optional"`
}

type NumQuery struct {
	Num uint `path:"num"`
}

type OrderItem struct {
	Column string `json:"column"`
	Value  string `json:"value,default=desc,optional,options=[desc,asc]"` // desc asc
}

type PathQuery struct {
	Path string `path:"path"`
}

type QueryDateContainsReq struct {
	ChannelUniqueId string `json:"channelUniqueId"`
	DeviceUniqueId  string `json:"deviceUniqueId"`
	Date            uint64 `json:"date"`
}

type QueryVideoRecordsReq struct {
	ChannelUniqueId string  `json:"channelUniqueId,optional"`
	DeviceUniqueId  string  `json:"deviceUniqueId,optional"`
	Page            uint64  `json:"page,optional"`
	Limit           uint64  `json:"limit,optional"`
	StartDate       uint64  `json:"startDate,optional"`
	EndDate         uint64  `json:"endDate,optional"`
	SortDate        *string `json:"sortDate,optional"`
	Urgent          *bool   `json:"urgent,optional"`
	SortUrgent      *string `json:"sortUrgent,optional"`
	Day             int64   `json:"day,optional"`
}

type RecordReq struct {
	Record map[string]interface{} `json:"record,optional"`
}

type RespQueryReq struct {
	Code string `json:"code"`
}

type ServerUpdateReq struct {
	Path string `json:"path"`
}

type SetEnvReq struct {
	Content string `json:"content"`
}

type SetPasswordReq struct {
	OldPassword string `json:"oldPassword"`
	Password    string `json:"password"`
}

type SetSMSConfigReq struct {
	Reboot bool                   `json:"reboot,optional"`
	Delay  int                    `json:"delay,optional"`
	IP     string                 `json:"ip"`
	Port   int                    `json:"port"`
	Config map[string]interface{} `json:"config,optional"`
}

type TRFParams struct {
	Columns        []string         `json:"columns,optional"`
	Orders         []*OrderItem     `json:"orders,optional"`
	Conditions     []*ConditionItem `json:"conditions,optional"`
	UniqueIds      []string         `json:"uniqueIds,optional"`
	Limit          int              `json:"limit,optional"`
	Page           int              `json:"page,optional"`
	Keyword        string           `json:"keyword,optional"`
	UniqueId       string           `json:"uniqueId,optional"`
	All            bool             `json:"all,optional"`
	Type           int64            `json:"type,optional"`
	IgnoreNotFound bool             `json:"ignoreNotFound,optional"`
	Data           []*UpdateItem    `json:"data,optional"`
	Backend        bool             `json:"backend,optional"`
}

type TypeQuery struct {
	Type uint `path:"type"`
}

type UniqueIdQuery struct {
	UniqueId string `path:"uniqueId"`
}

type UpdateItem struct {
	Column string      `json:"column"`
	Value  interface{} `json:"value"`
}

type UploadFileReq struct {
}

type VideoDeviceDownloadReq struct {
	UniqueId        string `json:"uniqueId"`
	ChannelUniqueId string `json:"channelUniqueId"`
	DeviceUniqueId  string `json:"deviceUniqueId"`
	StartAt         uint64 `json:"startAt"`
	EndAt           uint64 `json:"endAt"`
}

type VideoStreamInfoReq struct {
	StreamName string `path:"streamName"`
	ID         uint64 `path:"id"`
}
